import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import Nav from "./nav-client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <style>{`
          @media (max-width: 700px) {
            .main-nav { padding: 0.5rem 0.5rem !important; }
          }
          @media (min-width: 701px) {
            .main-nav { padding: 1rem 0 !important; }
          }
        `}</style>
      </head>
      <body className={inter.className} style={{ margin: 0, background: '#f7f7f9', minHeight: '100vh' }}>
        <Nav />
        <div style={{ paddingTop: '72px', minHeight: '100vh', width: '100%', maxWidth: 1000, margin: '0 auto' }}>{children}</div>
      </body>
    </html>
  );
}
